### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by unlight** [unlight/react-typescript-realworld-example-app#10]
- [ ] Use result in service, not in components
- [ ] Use tokens or njct
- [ ] App rename to pages
- [ ] Do not use commands (use case), just services???
- [ ] Folder stores
- [ ] Move to DataService or ArticleRepository
- [ ] Move all from api to feature folder
